# Generated by Django 5.2.12 on 2026-05-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hammers', 'Hammers'), ('nails', 'Nails'), ('iron sheets', 'Iron Sheets'), ('cement', 'Cement'), ('toolbox', 'Toolbox'), ('timber', 'Timber'), ('wire mesh', 'Wire Mesh')], max_length=255)),
                ('Quantity', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Total_Cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_on_credit', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('low_stock_threshold', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('nin', models.CharField(max_length=14)),
                ('stock_supplied', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stock')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='Supplier_Relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.supplier'),
        ),
    ]
