# Generated by Django 5.2.14 on 2026-05-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='Total_Cost',
            new_name='total_cost',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Supplier_Relationship',
        ),
    ]
