# Generated by Django 5.2.12 on 2026-05-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_date_stock_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(choices=[('hammers', 'Hammers'), ('nails', 'Nails'), ('iron sheets', 'Iron Sheets'), ('cement', 'Cement'), ('toolbox', 'Toolbox'), ('timber', 'Timber'), ('wire mesh', 'Wire Mesh')], max_length=25),
        ),
    ]
