# Generated by Django 5.2.14 on 2026-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_deleted_at_stock_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=20),
            preserve_default=False,
        ),
    ]
