# Generated by Django 5.2.12 on 2026-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_stock_deleted_at_remove_stock_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
