# Generated by Django 5.2.14 on 2026-05-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_expense_supplier_relationship_sale_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='Recorded_By',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Recorded_By',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_revenue',
        ),
        migrations.AlterField(
            model_name='sale',
            name='Comments',
            field=models.TextField(blank=True),
        ),
    ]
