# Generated by Django 5.2.14 on 2026-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_expense_recorded_by_remove_sale_recorded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
