# Generated by Django 5.2.14 on 2026-05-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_sale_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='Comments',
        ),
    ]
