# Generated by Django 5.2.12 on 2026-05-31 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_expense_price_expense_tax_amount_and_more'),
        ('stock', '0006_remove_stock_deleted_at_remove_stock_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCreditOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to='finance.customerprofile')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stock')),
            ],
        ),
    ]
