# Generated by Django 5.2.14 on 2026-06-01 12:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='delivery_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
    ]
