# Generated by Django 5.2.12 on 2026-06-02 07:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_sale_delivery_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='expense_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
