# Generated by Codex on 2026-06-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_sale_expense_amount_sale_net_profit'),
        ('stock', '0007_stock_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stock'),
        ),
    ]
