# Generated by Django 5.2.12 on 2026-05-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_customer_remove_customuser_is_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('sales_attendant', 'Sales Attendant'), ('store_manager', 'Store Manager'), ('accounts_admin', 'Accounts Admin')], default='customer', max_length=20),
        ),
    ]
