# Generated by Django 5.2.14 on 2026-06-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_nin_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('sales_attendant', 'Sales Attendant'), ('store_manager', 'Store Manager'), ('accounts_admin', 'Accounts Admin')], default='customer', max_length=20),
        ),
    ]
